// Subject: History
const subjectName = "General Studies";
const questions = [
  { q: "Who was the first President of India?", options: ["Dr. Rajendra Prasad", "Mahatma Gandhi", "Jawaharlal Nehru", "Sardar Patel"], answer: 0 },
  { q: "When did the Battle of Plassey take place?", options: ["1757", "1761", "1857", "1707"], answer: 0 },
  { q: "Who was the founder of the Maurya Dynasty?", options: ["Ashoka", "Chandragupta Maurya", "Bindusara", "Harshavardhana"], answer: 1 },
  { q: "The Quit India Movement was launched in which year?", options: ["1940", "1942", "1945", "1930"], answer: 1 },
  { q: "Who was the last Governor-General of independent India?", options: ["C. Rajagopalachari", "Lord Mountbatten", "Warren Hastings", "Rajendra Prasad"], answer: 0 },
  { q: "Who wrote the book 'Discovery of India'?", options: ["Jawaharlal Nehru", "Gandhi", "Ambedkar", "Subhas Chandra Bose"], answer: 0 },
  { q: "In which year did India become a republic?", options: ["1947", "1950", "1952", "1956"], answer: 1 },
  { q: "Who founded the Indian National Congress?", options: ["A.O. Hume", "M.G. Ranade", "Dadabhai Naoroji", "W.C. Bonnerjee"], answer: 0 },
  { q: "Where did the Jallianwala Bagh massacre take place?", options: ["Amritsar", "Delhi", "Kolkata", "Mumbai"], answer: 0 },
  { q: "Who was the first woman ruler of India?", options: ["Razia Sultana", "Indira Gandhi", "Nur Jahan", "Jhansi Rani"], answer: 0 },
  { q: "Who led the Salt March in 1930?", options: ["Gandhi", "Nehru", "Patel", "Rajagopalachari"], answer: 0 },
  { q: "Which Mughal emperor built the Red Fort?", options: ["Shah Jahan", "Akbar", "Jahangir", "Aurangzeb"], answer: 0 },
  { q: "In which year did the Revolt of 1857 start?", options: ["1856", "1857", "1858", "1860"], answer: 1 },
  { q: "Who was the first Governor-General of Bengal?", options: ["Warren Hastings", "Cornwallis", "Dalhousie", "Clive"], answer: 0 },
  { q: "Who was known as the Iron Man of India?", options: ["Sardar Patel", "Nehru", "Rajaji", "Bose"], answer: 0 },
  { q: "Which empire did Ashoka belong to?", options: ["Maurya", "Gupta", "Mughal", "Chola"], answer: 0 },
  { q: "What was the capital of the Maurya Empire?", options: ["Pataliputra", "Delhi", "Kolkata", "Ujjain"], answer: 0 },
  { q: "Who was the founder of the Gupta Dynasty?", options: ["Chandragupta I", "Samudragupta", "Skandagupta", "Harshavardhana"], answer: 0 },
  { q: "Which Indian freedom fighter was called 'Netaji'?", options: ["Subhas Chandra Bose", "Nehru", "Gokhale", "Tilak"], answer: 0 },
  { q: "Who started the Home Rule Movement?", options: ["Annie Besant", "Gandhi", "Nehru", "Tilak"], answer: 0 },


// Subject: Geography

  { q: "Which is the longest river in the world?", options: ["Nile", "Amazon", "Yangtze", "Mississippi"], answer: 0 },
  { q: "Mount Everest lies in which mountain range?", options: ["Andes", "Rockies", "Himalayas", "Alps"], answer: 2 },
  { q: "Which layer of the Earth lies just below the crust?", options: ["Core", "Mantle", "Outer core", "Asthenosphere"], answer: 1 },
  { q: "Which Indian state has the longest coastline?", options: ["Gujarat", "Tamil Nadu", "Andhra Pradesh", "Maharashtra"], answer: 0 },
  { q: "The Tropic of Cancer passes through how many states in India?", options: ["5", "6", "7", "8"], answer: 3 },
  { q: "What is the capital of Australia?", options: ["Canberra", "Sydney", "Melbourne", "Brisbane"], answer: 0 },
  { q: "Which is the smallest continent?", options: ["Australia", "Europe", "Antarctica", "South America"], answer: 0 },
  { q: "The Sahara Desert is located in which continent?", options: ["Africa", "Asia", "Australia", "South America"], answer: 0 },
  { q: "Which Indian river is known as the 'Dakshina Ganga'?", options: ["Godavari", "Krishna", "Kaveri", "Narmada"], answer: 0 },
  { q: "Which planet is known as the Earth's twin?", options: ["Venus", "Mars", "Mercury", "Jupiter"], answer: 0 },
  { q: "Which river originates from Amarkantak?", options: ["Narmada", "Tapti", "Godavari", "Mahanadi"], answer: 0 },
  { q: "The standard meridian of India is?", options: ["82.5° E", "80.5° E", "75.5° E", "90° E"], answer: 0 },
  { q: "Which is the highest dam in India?", options: ["Tehri", "Bhakra Nangal", "Sardar Sarovar", "Hirakud"], answer: 0 },
  { q: "Which state is known as the 'Spice Garden of India'?", options: ["Kerala", "Tamil Nadu", "Assam", "Goa"], answer: 0 },
  { q: "Which island group lies to the southwest of India?", options: ["Lakshadweep", "Andaman", "Nicobar", "Minicoy"], answer: 0 },
  { q: "Which is the southernmost point of India?", options: ["Indira Point", "Kanyakumari", "Rameswaram", "Nicobar"], answer: 0 },
  { q: "Which Indian state shares boundary with the most states?", options: ["Uttar Pradesh", "Madhya Pradesh", "Bihar", "Chhattisgarh"], answer: 0 },
  { q: "What is the term for the point inside the Earth where an earthquake starts?", options: ["Focus", "Epicenter", "Crust", "Seismic point"], answer: 0 },
  { q: "Which gas is most abundant in Earth's atmosphere?", options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"], answer: 0 },
  { q: "Which line divides India into northern and southern parts?", options: ["Tropic of Cancer", "Equator", "Prime Meridian", "Latitude 25°"], answer: 0 },

// Subject: Science

  { q: "What is the chemical symbol for water?", options: ["H2O", "O2", "CO2", "NaCl"], answer: 0 },
  { q: "Which planet is known as the Red Planet?", options: ["Earth", "Mars", "Jupiter", "Saturn"], answer: 1 },
  { q: "What part of the cell contains genetic material?", options: ["Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"], answer: 0 },
  { q: "Which gas do plants absorb during photosynthesis?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], answer: 1 },
  { q: "What is the hardest natural substance on Earth?", options: ["Diamond", "Gold", "Iron", "Platinum"], answer: 0 },
  { q: "What is the chemical formula for methane?", options: ["CH4", "C2H6", "CO2", "O2"], answer: 0 },
  { q: "Which vitamin is produced by sunlight in human skin?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], answer: 3 },
  { q: "What is the main component of the sun?", options: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon"], answer: 1 },
  { q: "Which element is a major component of proteins?", options: ["Oxygen", "Carbon", "Nitrogen", "Hydrogen"], answer: 2 },
  { q: "What type of bond holds the atoms in a water molecule together?", options: ["Ionic bond", "Covalent bond", "Hydrogen bond", "Metallic bond"], answer: 1 },
  { q: "Which is the largest organ in the human body?", options: ["Brain", "Heart", "Liver", "Skin"], answer: 3 },
  { q: "What is the process by which plants make their food?", options: ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"], answer: 1 },
  { q: "What is the atomic number of oxygen?", options: ["6", "7", "8", "9"], answer: 2 },
  { q: "Which of the following is a non-metal?", options: ["Iron", "Copper", "Sulfur", "Aluminum"], answer: 2 },
  { q: "What is the unit of electric current?", options: ["Volt", "Ampere", "Ohm", "Joule"], answer: 1 },
  { q: "What does DNA stand for?", options: ["Deoxyribonucleic Acid", "Deoxyribose Acid", "Dihydroxy Acid", "Deoxy Acid"], answer: 0 },
  { q: "What is the boiling point of water in Celsius?", options: ["90°C", "100°C", "110°C", "120°C"], answer: 1 },
  { q: "Which planet is closest to the Sun?", options: ["Earth", "Mars", "Mercury", "Venus"], answer: 2 },
  { q: "Which organ in the human body is primarily responsible for filtering blood?", options: ["Liver", "Kidney", "Heart", "Lungs"], answer: 1 },
  { q: "Which of the following is an example of a noble gas?", options: ["Oxygen", "Hydrogen", "Neon", "Nitrogen"], answer: 2 },


// Subject: Reasoning

  { q: "If 2 pencils cost 30 cents, how much would 6 pencils cost?", options: ["60 cents", "90 cents", "120 cents", "180 cents"], answer: 0 },
  { q: "What is the next number in the sequence: 1, 4, 9, 16, ?", options: ["20", "25", "30", "36"], answer: 1 },
  { q: "Which of the following is the odd one out?", options: ["Apple", "Banana", "Orange", "Potato"], answer: 3 },
  { q: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1 },
  { q: "If 'A' is coded as 1, 'B' as 2, 'C' as 3, then what is 'Z' coded as?", options: ["24", "25", "26", "27"], answer: 2 },
  { q: "Which of the following is a synonym for 'Quick'?", options: ["Fast", "Slow", "Tired", "Loud"], answer: 0 },
  { q: "Which of the following numbers is a multiple of 12?", options: ["24", "26", "28", "30"], answer: 0 },
  { q: "If the day before yesterday was Wednesday, what day will it be tomorrow?", options: ["Friday", "Saturday", "Sunday", "Monday"], answer: 3 },
  { q: "What comes next in the pattern: J, F, M, A, M, ?", options: ["J", "F", "J", "M"], answer: 0 },
  { q: "Which number is missing in the sequence: 5, 10, 15, ?, 25", options: ["20", "30", "40", "50"], answer: 0 },
  { q: "If all dogs are animals and all animals are living beings, which of the following statements is correct?", options: ["All dogs are living beings", "All animals are dogs", "Some animals are dogs", "No animals are dogs"], answer: 0 },
  { q: "Which of the following is the next letter in the sequence: D, F, H, J, ?", options: ["K", "L", "M", "N"], answer: 0 },
  { q: "If a box contains 5 red balls, 8 green balls, and 3 blue balls, how many balls are there in total?", options: ["10", "12", "15", "16"], answer: 2 },
  { q: "Which number is not divisible by 5?", options: ["10", "25", "30", "44"], answer: 3 },
  { q: "Which of the following shapes has only one side?", options: ["Circle", "Triangle", "Square", "Rectangle"], answer: 0 },
  { q: "What comes next in the sequence: 2, 4, 8, 16, ?", options: ["32", "64", "128", "256"], answer: 0 },
  { q: "How many months have 28 days?", options: ["1", "2", "12", "0"], answer: 2 },
  { q: "What is the next letter in the series: B, D, F, H, ?", options: ["I", "J", "K", "L"], answer: 0 },
  { q: "What comes next in the series: 7, 14, 21, 28, ?", options: ["34", "36", "35", "42"], answer: 3 },
  { q: "Which of the following is the opposite of 'Friend'?", options: ["Enemy", "Stranger", "Rival", "Neighbor"], answer: 0 },


// Subject: Polity

  { q: "Who is the first citizen of India?", options: ["President", "Prime Minister", "Speaker", "Governor"], answer: 0 },
  { q: "What is the minimum age required to become the President of India?", options: ["30", "35", "40", "45"], answer: 1 },
  { q: "Which article of the Indian Constitution deals with the Right to Equality?", options: ["Article 14", "Article 15", "Article 16", "Article 17"], answer: 0 },
  { q: "Which body has the power to remove the President of India?", options: ["Supreme Court", "Lok Sabha", "Rajya Sabha", "Parliament"], answer: 3 },
  { q: "Which is the highest judicial body in India?", options: ["Supreme Court", "High Court", "District Court", "Session Court"], answer: 0 },
  { q: "Who is known as the Father of the Indian Constitution?", options: ["Mahatma Gandhi", "Jawaharlal Nehru", "Dr. B.R. Ambedkar", "Sardar Patel"], answer: 2 },
  { q: "What is the minimum age required to become the Prime Minister of India?", options: ["30", "35", "40", "45"], answer: 1 },
  { q: "Who is the current Vice-President of India?", options: ["M. Venkaiah Naidu", "Rajnath Singh", "Amit Shah", "Narendra Modi"], answer: 0 },
  { q: "Which part of the Indian Constitution describes the Fundamental Rights?", options: ["Part I", "Part III", "Part IV", "Part V"], answer: 1 },
  { q: "Which of the following is NOT a fundamental right in India?", options: ["Right to Property", "Right to Education", "Right to Equality", "Right to Freedom of Speech"], answer: 0 },
  { q: "Who appoints the Governor of a state in India?", options: ["Prime Minister", "President", "Chief Justice", "Speaker"], answer: 1 },
  { q: "How many members are there in the Rajya Sabha?", options: ["245", "250", "200", "225"], answer: 0 },
  { q: "Which is the largest state in India by area?", options: ["Madhya Pradesh", "Rajasthan", "Uttar Pradesh", "Maharashtra"], answer: 1 },
  { q: "In which year was the Indian Constitution adopted?", options: ["1946", "1947", "1949", "1950"], answer: 2 },
  { q: "Which of the following is a Union Territory of India?", options: ["Goa", "Sikkim", "Delhi", "Uttarakhand"], answer: 2 },
  { q: "Who can dissolve the Lok Sabha?", options: ["President", "Prime Minister", "Chief Justice", "Speaker of the House"], answer: 0 },
  { q: "How many types of emergencies are there in India?", options: ["1", "2", "3", "4"], answer: 2 },
  { q: "Which of the following is NOT a feature of the Indian Constitution?", options: ["Single Citizenship", "Secularism", "Unicameral Legislature", "Parliamentary System"], answer: 2 },
  { q: "Who is the head of the State in India?", options: ["Prime Minister", "President", "Chief Justice", "Governor"], answer: 1 },

];
