const subjectName = "Soil";  // You can change this to any subjec
const questions = [
  // === HISTORY ===
  { subject: "History", question: "Who was the first Governor-General of independent India?", options: ["Rajendra Prasad", "Jawaharlal Nehru", "C. Rajagopalachari", "Lord Mountbatten"], answer: "Lord Mountbatten" },
  { subject: "History", question: "The revolt of 1857 began in which city?", options: ["Delhi", "Meerut", "Lucknow", "Kanpur"], answer: "Meerut" },
  { subject: "History", question: "Who was the founder of the Maurya Empire?", options: ["Ashoka", "Bindusara", "Chandragupta Maurya", "Bimbisara"], answer: "Chandragupta Maurya" },
  { subject: "History", question: "Which Mughal emperor built the Taj Mahal?", options: ["Babur", "Shah Jahan", "Akbar", "Aurangzeb"], answer: "Shah Jahan" },
  { subject: "History", question: "Who led the Salt March in 1930?", options: ["Sardar Patel", "Jawaharlal Nehru", "Subhash Chandra Bose", "Mahatma Gandhi"], answer: "Mahatma Gandhi" },
  { subject: "History", question: "In which year did India become a republic?", options: ["1947", "1950", "1948", "1952"], answer: "1950" },
  { subject: "History", question: "Who was the first President of India?", options: ["Rajendra Prasad", "S. Radhakrishnan", "Zakir Husain", "V. V. Giri"], answer: "Rajendra Prasad" },
  { subject: "History", question: "Which movement is associated with 'Do or Die'?", options: ["Civil Disobedience", "Quit India", "Non-Cooperation", "Swadeshi"], answer: "Quit India" },
  { subject: "History", question: "Which dynasty ruled India before the British?", options: ["Mughals", "Guptas", "Mauryas", "Cholas"], answer: "Mughals" },
  { subject: "History", question: "Where did the Jallianwala Bagh massacre happen?", options: ["Amritsar", "Lahore", "Delhi", "Lucknow"], answer: "Amritsar" },
  { subject: "History", question: "Who was known as the 'Iron Man of India'?", options: ["Bhagat Singh", "Sardar Vallabhbhai Patel", "B. R. Ambedkar", "Subhas Bose"], answer: "Sardar Vallabhbhai Patel" },
  { subject: "History", question: "Which Congress session declared 'Purna Swaraj'?", options: ["Mumbai", "Lahore", "Delhi", "Kolkata"], answer: "Lahore" },
  { subject: "History", question: "Who composed Vande Mataram?", options: ["Rabindranath Tagore", "Bankim Chandra Chatterjee", "Subramania Bharati", "Sarojini Naidu"], answer: "Bankim Chandra Chatterjee" },
  { subject: "History", question: "Who was the first woman ruler of Delhi?", options: ["Razia Sultana", "Nur Jahan", "Rani Durgavati", "Jhansi Rani"], answer: "Razia Sultana" },
  { subject: "History", question: "Which empire built the Qutub Minar?", options: ["Slave Dynasty", "Mughal", "Maurya", "Gupta"], answer: "Slave Dynasty" },
  { subject: "History", question: "Who introduced the Permanent Settlement in India?", options: ["Lord Dalhousie", "Warren Hastings", "Lord Cornwallis", "Robert Clive"], answer: "Lord Cornwallis" },
  { subject: "History", question: "Where was the first Indian National Congress held?", options: ["Bombay", "Madras", "Delhi", "Calcutta"], answer: "Bombay" },
  { subject: "History", question: "When did the Battle of Plassey take place?", options: ["1757", "1857", "1764", "1800"], answer: "1757" },
  { subject: "History", question: "Who was the last Viceroy of British India?", options: ["Lord Mountbatten", "Lord Wavell", "Lord Curzon", "Lord Irwin"], answer: "Lord Mountbatten" },
  { subject: "History", question: "Which leader is called the 'Father of Indian Renaissance'?", options: ["Raja Ram Mohan Roy", "Dayanand Saraswati", "Swami Vivekananda", "Ishwar Chandra Vidyasagar"], answer: "Raja Ram Mohan Roy" },

  // === ECONOMICS ===
  { subject: "Economics", question: "What is the full form of GDP?", options: ["Gross Domestic Product", "Global Development Project", "Government Debt Profile", "Gross Demand Potential"], answer: "Gross Domestic Product" },
  { subject: "Economics", question: "Which sector includes farming?", options: ["Primary", "Secondary", "Tertiary", "Quaternary"], answer: "Primary" },
  { subject: "Economics", question: "Which organization prints currency in India?", options: ["NABARD", "RBI", "SEBI", "Finance Ministry"], answer: "RBI" },
  { subject: "Economics", question: "Which is a direct tax?", options: ["GST", "Income Tax", "Sales Tax", "Customs Duty"], answer: "Income Tax" },
  { subject: "Economics", question: "What is inflation?", options: ["Decrease in prices", "Increase in prices", "Stable prices", "Price control"], answer: "Increase in prices" },
  { subject: "Economics", question: "What does demand mean?", options: ["Desire to buy", "Ability to buy", "Willingness and ability to buy", "Government policy"], answer: "Willingness and ability to buy" },
  { subject: "Economics", question: "Which is the apex bank of India?", options: ["SBI", "RBI", "PNB", "ICICI"], answer: "RBI" },
  { subject: "Economics", question: "When was GST implemented?", options: ["2015", "2016", "2017", "2018"], answer: "2017" },
  { subject: "Economics", question: "What is the term for an economy with both private and public sectors?", options: ["Open Economy", "Mixed Economy", "Capitalist Economy", "Traditional Economy"], answer: "Mixed Economy" },
  { subject: "Economics", question: "Which sector is fastest growing in India?", options: ["Agriculture", "Industry", "Services", "Fisheries"], answer: "Services" },
  { subject: "Economics", question: "Which program guarantees 100 days of wage employment?", options: ["PMGSY", "MGNREGA", "PMAY", "NSAP"], answer: "MGNREGA" },
  { subject: "Economics", question: "Which is the largest component of India's GDP?", options: ["Agriculture", "Industry", "Services", "Mining"], answer: "Services" },
  { subject: "Economics", question: "What is a fiscal deficit?", options: ["Revenue > Expenditure", "Expenditure > Revenue", "Balanced Budget", "No spending"], answer: "Expenditure > Revenue" },
  { subject: "Economics", question: "Who prepares the Union Budget?", options: ["RBI", "NITI Aayog", "Finance Minister", "President"], answer: "Finance Minister" },
  { subject: "Economics", question: "Which is an example of a renewable resource?", options: ["Coal", "Petroleum", "Wind Energy", "Uranium"], answer: "Wind Energy" },
  { subject: "Economics", question: "Disguised unemployment is mostly found in?", options: ["Cities", "Agriculture", "Industries", "IT sector"], answer: "Agriculture" },
  { subject: "Economics", question: "What is the aim of 'Make in India'?", options: ["Promote services", "Promote manufacturing", "Import goods", "Subsidize exports"], answer: "Promote manufacturing" },
  { subject: "Economics", question: "The value of all goods and services produced in a year is?", options: ["GNP", "NDP", "GDP", "NNP"], answer: "GDP" },
  { subject: "Economics", question: "Currency devaluation affects?", options: ["Imports", "Exports", "Savings", "Loans"], answer: "Imports" },
  { subject: "Economics", question: "Which indicator shows living standard?", options: ["GDP", "HDI", "GNP", "CPI"], answer: "HDI" },

  // === SCIENCE ===
  { subject: "Science", question: "Which gas is essential for photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: "Carbon Dioxide" },
  { subject: "Science", question: "What is the boiling point of water?", options: ["100°C", "0°C", "50°C", "212°F"], answer: "100°C" },
  { subject: "Science", question: "Which vitamin is made in the skin when exposed to sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], answer: "Vitamin D" },
  { subject: "Science", question: "The powerhouse of the cell is?", options: ["Ribosome", "Nucleus", "Mitochondria", "Chloroplast"], answer: "Mitochondria" },
  { subject: "Science", question: "What is H2O?", options: ["Oxygen", "Hydrogen", "Water", "Salt"], answer: "Water" },
  { subject: "Science", question: "What is the chemical symbol for Sodium?", options: ["Na", "So", "S", "Sn"], answer: "Na" },
  { subject: "Science", question: "Which planet is called the Red Planet?", options: ["Mars", "Venus", "Jupiter", "Saturn"], answer: "Mars" },
  { subject: "Science", question: "What is Newton’s third law?", options: ["F=ma", "Energy is conserved", "Every action has equal and opposite reaction", "Objects at rest stay at rest"], answer: "Every action has equal and opposite reaction" },
  { subject: "Science", question: "Which part of the plant conducts photosynthesis?", options: ["Root", "Stem", "Leaf", "Flower"], answer: "Leaf" },
  { subject: "Science", question: "Which organ pumps blood in the human body?", options: ["Lungs", "Liver", "Heart", "Brain"], answer: "Heart" },
  { subject: "Science", question: "What is the main gas in Earth’s atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Hydrogen", "Nitrogen"], answer: "Nitrogen" },
  { subject: "Science", question: "Which metal is liquid at room temperature?", options: ["Mercury", "Iron", "Gold", "Silver"], answer: "Mercury" },
  { subject: "Science", question: "Which organ controls all body functions?", options: ["Heart", "Brain", "Lungs", "Kidneys"], answer: "Brain" },
  { subject: "Science", question: "Which force pulls objects toward the Earth?", options: ["Magnetism", "Electricity", "Gravity", "Friction"], answer: "Gravity" },
  { subject: "Science", question: "What type of energy is stored in food?", options: ["Kinetic", "Chemical", "Nuclear", "Thermal"], answer: "Chemical" },
  { subject: "Science", question: "How many legs does an insect have?", options: ["4", "6", "8", "10"], answer: "6" },
  { subject: "Science", question: "The sun is a?", options: ["Planet", "Star", "Moon", "Asteroid"], answer: "Star" },
  { subject: "Science", question: "Which of these is a vertebrate?", options: ["Frog", "Earthworm", "Spider", "Snail"], answer: "Frog" },
  { subject: "Science", question: "Which human sense organ detects smell?", options: ["Eyes", "Ears", "Nose", "Skin"], answer: "Nose" },
  { subject: "Science", question: "What do bees collect from flowers?", options: ["Water", "Nectar", "Seeds", "Leaves"], answer: "Nectar" },

// === MATH ===
  { subject: "Math", question: "What is 12 × 8?", options: ["96", "88", "108", "98"], answer: "96" },
  { subject: "Math", question: "What is the square root of 144?", options: ["12", "14", "16", "18"], answer: "12" },
  { subject: "Math", question: "Solve: 15 + 6 × 2", options: ["42", "21", "27", "30"], answer: "27" },
  { subject: "Math", question: "What is 1/2 of 100?", options: ["25", "50", "20", "40"], answer: "50" },
  { subject: "Math", question: "What is the formula for the area of a triangle?", options: ["½ × base × height", "base × height", "2 × base × height", "base + height"], answer: "½ × base × height" },
  { subject: "Math", question: "What is 9 squared?", options: ["81", "72", "90", "100"], answer: "81" },
  { subject: "Math", question: "What is the value of π (pi)?", options: ["3.14", "2.17", "1.62", "4.13"], answer: "3.14" },
  { subject: "Math", question: "What is the perimeter of a square with side 5 cm?", options: ["25 cm", "20 cm", "10 cm", "15 cm"], answer: "20 cm" },
  { subject: "Math", question: "If x = 2, what is the value of 3x + 4?", options: ["10", "11", "12", "14"], answer: "10" },
  { subject: "Math", question: "What is 75% of 200?", options: ["100", "120", "150", "175"], answer: "150" },
  { subject: "Math", question: "How many degrees in a triangle?", options: ["180", "360", "90", "270"], answer: "180" },
  { subject: "Math", question: "What is 0.5 as a fraction?", options: ["1/2", "1/4", "3/4", "2/3"], answer: "1/2" },
  { subject: "Math", question: "What is the cube of 3?", options: ["27", "9", "18", "81"], answer: "27" },
  { subject: "Math", question: "Which is a prime number?", options: ["4", "6", "7", "8"], answer: "7" },
  { subject: "Math", question: "What is the LCM of 4 and 5?", options: ["10", "15", "20", "25"], answer: "20" },
  { subject: "Math", question: "What is the mode in [3, 3, 6, 9, 3, 5]?", options: ["3", "6", "5", "9"], answer: "3" },
  { subject: "Math", question: "What is 100 divided by 4?", options: ["20", "25", "30", "40"], answer: "25" },
  { subject: "Math", question: "Which is the smallest positive integer?", options: ["0", "1", "-1", "2"], answer: "1" },
  { subject: "Math", question: "What is the average of 10, 20, and 30?", options: ["15", "20", "25", "30"], answer: "20" },
  { subject: "Math", question: "Convert 0.25 to percentage.", options: ["2.5%", "25%", "75%", "50%"], answer: "25%" },

// === GEOGRAPHY ===
  { subject: "Geography", question: "Which is the largest continent?", options: ["Africa", "Asia", "Europe", "North America"], answer: "Asia" },
  { subject: "Geography", question: "Which is the longest river in the world?", options: ["Nile", "Amazon", "Ganga", "Yangtze"], answer: "Nile" },
  { subject: "Geography", question: "Which is the highest mountain peak?", options: ["Kanchenjunga", "K2", "Mount Everest", "Nanda Devi"], answer: "Mount Everest" },
  { subject: "Geography", question: "Which is the smallest ocean?", options: ["Arctic", "Indian", "Pacific", "Atlantic"], answer: "Arctic" },
  { subject: "Geography", question: "Which Indian river is known as the 'Sorrow of Bihar'?", options: ["Ganga", "Kosi", "Yamuna", "Brahmaputra"], answer: "Kosi" },
  { subject: "Geography", question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], answer: "Canberra" },
  { subject: "Geography", question: "Which planet is known as the Earth’s twin?", options: ["Mars", "Venus", "Jupiter", "Saturn"], answer: "Venus" },
  { subject: "Geography", question: "Which is the largest desert?", options: ["Sahara", "Thar", "Gobi", "Kalahari"], answer: "Sahara" },
  { subject: "Geography", question: "Which Indian state has the longest coastline?", options: ["Tamil Nadu", "Andhra Pradesh", "Gujarat", "Maharashtra"], answer: "Gujarat" },
  { subject: "Geography", question: "The Tropic of Cancer passes through how many Indian states?", options: ["6", "7", "8", "9"], answer: "8" },
  { subject: "Geography", question: "Which country is known as the Land of the Rising Sun?", options: ["China", "Japan", "Korea", "Thailand"], answer: "Japan" },
  { subject: "Geography", question: "What is the standard time of India?", options: ["GMT+5", "GMT+5:30", "GMT+6", "GMT+4"], answer: "GMT+5:30" },
  { subject: "Geography", question: "Which river flows through Paris?", options: ["Danube", "Seine", "Rhine", "Thames"], answer: "Seine" },
  { subject: "Geography", question: "Which ocean is on India's west?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], answer: "Indian" },
  { subject: "Geography", question: "Where is the Great Barrier Reef?", options: ["India", "Brazil", "Australia", "USA"], answer: "Australia" },
  { subject: "Geography", question: "Which Indian city is called the City of Lakes?", options: ["Udaipur", "Bhopal", "Jaipur", "Lucknow"], answer: "Udaipur" },
  { subject: "Geography", question: "Which layer of Earth is liquid?", options: ["Crust", "Mantle", "Outer core", "Inner core"], answer: "Outer core" },
  { subject: "Geography", question: "What is the shape of Earth?", options: ["Flat", "Round", "Oval", "Oblate spheroid"], answer: "Oblate spheroid" },
  { subject: "Geography", question: "Which is the southernmost point of India?", options: ["Kanyakumari", "Rameswaram", "Indira Point", "Minicoy"], answer: "Indira Point" },
  { subject: "Geography", question: "What is the main occupation of people in rural India?", options: ["Farming", "Teaching", "Trading", "Construction"], answer: "Farming" }
];
